#!/usr/bin/env python3
"""Compatible CLI and Python exports for the modular release workflow."""
from anime_release.legacy_models import ResolvedAnime
from anime_release.legacy_models import IdentityResolution
from anime_release.queries import now_iso
from anime_release.queries import norm
from anime_release.queries import unique
from anime_release.queries import lookup_nickname_alias
from anime_release.queries import emit_json
from anime_release.queries import contains_cjk
from anime_release.queries import has_latin_search_text
from anime_release.queries import is_latin_search_title
from anime_release.queries import latin_search_titles
from anime_release.queries import search_name_score
from anime_release.queries import is_redundant_search_name
from anime_release.queries import is_obviously_damaged_search_name
from anime_release.queries import broad_search_name
from anime_release.queries import select_search_names
from anime_release.queries import strict_zh_search_names
from anime_release.queries import promote_search_titles
from anime_release.legacy_state import names_for
from anime_release.legacy_state import find_show_by_identity
from anime_release.legacy_state import find_show
from anime_release.legacy_state import _name_position
from anime_release.legacy_state import detect_tracked_titles
from anime_release.legacy_state import alias_mentions_multiple_canonical_titles
from anime_release.legacy_state import sanitize_state_aliases
from anime_release.legacy_state import delete_show
from anime_release.legacy_state import upsert_show
from anime_release.providers import current_anime_season
from anime_release.providers import anilist_request
from anime_release.providers import anilist_media_request
from anime_release.providers import anilist_air_date_request
from anime_release.providers import bangumi_request
from anime_release.providers import bangumi_infobox_values
from anime_release.providers import bangumi_item_names
from anime_release.providers import bangumi_item_is_current
from anime_release.providers import bangumi_item_to_resolved
from anime_release.providers import resolve_bangumi_title
from anime_release.providers import resolved_from_state
from anime_release.providers import name_score
from anime_release.providers import infer_season
from anime_release.providers import canonical_season
from anime_release.providers import related_anime_titles
from anime_release.providers import continuation_parts_from_media
from anime_release.providers import mainline_scope_from_media
from anime_release.providers import media_to_resolved
from anime_release.providers import resolve_title
from anime_release.metadata import schedule_cache_key
from anime_release.metadata import load_schedule_cache
from anime_release.metadata import save_schedule_cache
from anime_release.metadata import resolved_snapshot
from anime_release.metadata import resolved_from_snapshot
from anime_release.metadata import read_schedule_snapshot
from anime_release.metadata import write_schedule_snapshot
from anime_release.metadata import write_schedule_snapshots
from anime_release.metadata import official_air_date_cache_key
from anime_release.metadata import read_official_air_date_cache
from anime_release.metadata import write_official_air_date_cache
from anime_release.metadata import metadata_identity_conflicts
from anime_release.metadata import merge_resolved
from anime_release.metadata import metadata_queries
from anime_release.metadata import hydrate_airing_metadata
from anime_release.metadata import ensure_official_air_identity
from anime_release.metadata import official_air_date_report
from anime_release.metadata import next_airing_context
from anime_release.metadata import completed_part_context
from anime_release.metadata import render_not_aired_reply
from anime_release.metadata import render_part_finished_reply
from anime_release.metadata import latest_regular_target
from anime_release.retrieval import build_search_args
from anime_release.presentation import selected_view
from anime_release.presentation import is_final_episode
from anime_release.presentation import result_output_contract
from anime_release.presentation import quality_compatibility
from anime_release.presentation import render_result_reply
from anime_release.presentation import render_latest_already_handled_reply
from anime_release.presentation import render_season_batch_reply
from anime_release.presentation import render_failure_reply
from anime_release.presentation import render_quality_fallback_question
from anime_release.presentation import premium_source_type
from anime_release.presentation import render_quality_upgrade_question
from anime_release.identity import bridge_to_tracked_show
from anime_release.identity import input_kind_for
from anime_release.identity import resolver_failure
from anime_release.identity import resolve_work_identity
from anime_release.presentation import identity_conflict_report
from anime_release.presentation import identity_report_fields
from anime_release.batch import child_argv_from_args
from anime_release.batch import render_batch_child_status
from anime_release.batch import run_tracked_title_batch
from anime_release.cli import build_parser
from anime_release.cli import status_return_code
from anime_release.cli import main
from anime_release.settings import *
from state_io import load_state, save_state
from release_search_core import SearchContext, SearchIntent, search_release_report
from qbittorrent_submit import submit_magnet, SubmissionError
import time
import urllib.error
from datetime import date

if __name__ == "__main__":
    raise SystemExit(main())
